title: Data Radar
logo: "assets/radarLogoTitle.svg"
email: florian_kl@t-online.de
description: >- # this means to ignore newlines until "baseurl:"
  Auf dieser Seite bekommen Sie einen Überblick über die Verwendung, Konfiguration und Entwicklung des Radars.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: flnkln
github_username:  flnkln

# Build settings
# theme: minima

# Theme
remote_theme: pmarsceill/just-the-docs
# theme: just-the-docs

color_scheme: radar
# search_enabled: false
